### PR TITLE
fix(BAC-48):

### PR DESCRIPTION
**Pull request by madvirus-ops**
general code overview
variables renamed
and so on

### CODE REVIEW

**Comment by Idimmusix** [comment]
I believe merging this branch is no longer important, can we delete the pull request in peace

**Comment by madvirus-ops** [comment]
There's no major change in this sha, just variable ls renamed

**Comment by madvirus-ops** [comment]
@Idimmusix  @trustedcoder

**Review by Idimmusix — APPROVED** [review]
the change form base.metadata.create_all(engine) to just middleware, hope it won't affect the code?
Let's try it

**Comment by madvirus-ops** [comment]
Let's try it

**Pull request merged**
